name: Test

on:
  push:
    branches:
      - main

concurrency: ${{ github.ref }}

jobs:
  build:
    name: Test ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [prisma-errors-core, prisma-errors-nest]
    steps:
      - name: Check out the code 🗄
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-environment

      - name: Lint the code 🕵
        run: yarn nx lint ${{ matrix.project }}

      - name: Check the prettiness of the code 💅
        run: yarn prettier:check ${{ matrix.project }}

      - name: Run database
        run: |
          yarn compose-up
          yarn prisma:generate
          yarn prisma:migrate:deploy

      - name: Run unit tests 🧪
        run: yarn nx test ${{ matrix.project }}

      - name: Build code 🛠
        run: yarn nx build ${{ matrix.project }}
