name: Test

on:
  push:
    branches-ignore:
      - main

concurrency: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code 🗄
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-environment

      - name: Lint the code 🕵
        run: yarn lint prisma-errors-core

      - name: Check the prettiness of the code 💅
        run: yarn prettier:check

      - name: Run database
        run: |
          yarn compose-up
          sleep 10
          yarn prisma:generate
          yarn prisma:migrate:deploy

      - name: Run unit tests 🧪
        run: yarn test prisma-errors-core

      - name: Build code 🛠
        run: yarn build prisma-errors-core
